# Generated by Django 5.2.17 on 2026-10-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_accountemail_profile_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a JPG, PNG or WebP car photo. Clear it to restore the sample image.', upload_to='cars/'),
        ),
    ]
